name: CPS
version: 1.1
api: [3.0.0]
mcpe-protocol: 486
author: iRainDrop
main: iRainDrop\CPS\Main
description: CPS
commands:
  cps:
    usage: "§cUsage: /cps <on/off>"
    description: Enable/Disable your CPS Counter popup
